// <auto-generated />
using System;
using DatLichKhamBenh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatLichKhamBenh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatLichKhamBenh.Models.BacSi", b =>
                {
                    b.Property<int>("MaBacSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBacSi"));

                    b.Property<decimal>("GiaKham")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MaBacSi");

                    b.HasIndex("MaChuyenKhoa");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("BacSi");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.CauHinhEmail", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<bool>("BatEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SenderPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaCauHinh");

                    b.ToTable("CauHinhEmail");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("MaChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenKhoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuyenKhoa");

                    b.ToTable("ChuyenKhoa");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.HoSoBenhAn", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DonThuoc")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LoiKhuyen")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaLichHen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaLichHen")
                        .IsUnique();

                    b.ToTable("HoSoBenhAn");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.LichHen", b =>
                {
                    b.Property<int>("MaLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHen"));

                    b.Property<TimeSpan>("GioKham")
                        .HasColumnType("time");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaBacSi", "NgayKham", "GioKham")
                        .IsUnique()
                        .HasFilter("[TrangThai] <> 'DaHuy'");

                    b.ToTable("LichHen");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<bool>("DaKhoa")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.BacSi", b =>
                {
                    b.HasOne("DatLichKhamBenh.Models.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("DanhSachBacSi")
                        .HasForeignKey("MaChuyenKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatLichKhamBenh.Models.NguoiDung", "NguoiDung")
                        .WithOne("BacSi")
                        .HasForeignKey("DatLichKhamBenh.Models.BacSi", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoa");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.BenhNhan", b =>
                {
                    b.HasOne("DatLichKhamBenh.Models.NguoiDung", "NguoiDung")
                        .WithOne("BenhNhan")
                        .HasForeignKey("DatLichKhamBenh.Models.BenhNhan", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.HoSoBenhAn", b =>
                {
                    b.HasOne("DatLichKhamBenh.Models.LichHen", "LichHen")
                        .WithOne("HoSoBenhAn")
                        .HasForeignKey("DatLichKhamBenh.Models.HoSoBenhAn", "MaLichHen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.LichHen", b =>
                {
                    b.HasOne("DatLichKhamBenh.Models.BacSi", "BacSi")
                        .WithMany("DanhSachLichHen")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatLichKhamBenh.Models.BenhNhan", "BenhNhan")
                        .WithMany("DanhSachLichHen")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.BacSi", b =>
                {
                    b.Navigation("DanhSachLichHen");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.BenhNhan", b =>
                {
                    b.Navigation("DanhSachLichHen");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("DanhSachBacSi");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.LichHen", b =>
                {
                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("DatLichKhamBenh.Models.NguoiDung", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });
#pragma warning restore 612, 618
        }
    }
}
